# Generated by Django 5.2.4 on 2025-08-17 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_rename_content_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='profile/'),
        ),
    ]
